package com.istu.schedule.util

object NavDestinations {
    const val ONBOARDING_PAGE = "ONBOARDING_PAGE"
    const val MAIN_PAGE = "MAIN_PAGE"
    const val PROJECT_PAGE = "PROJECT_PAGE"
    const val FILTERS_PAGE = "FILTERS_PAGE"
    const val ACCOUNT_PAGE = "CANDIDATE_PAGE"
    const val CANDIDATE_PROJECTS_PAGE = "CANDIDATE_PROJECTS_PAGE"
    const val CANDIDATE_PARTICIPATIONS_PAGE = "CANDIDATE_PARTICIPATIONS_PAGE"
    const val BINDING_PAGE = "BINDING_PAGE"
    const val LANGUAGE_PAGE = "LANGUAGE_PAGE"
    const val PROJFAIR_LOGIN_PAGE = "PROJFAIR_LOGIN_PAGE"
    const val THEME_PAGE = "THEME_PAGE"
}
